version: "3.8"

services:
    postgres:
        image: "postgres:14.2"
        volumes:
            - "./postgres_data:/var/lib/postgresql/data"
        environment:
            - POSTGRES_PASSWORD=docker
            - POSTGRES_USER=docker
        ports:
            - "5432:5432"
